# Thanks to ChocolateBread799
# https://github.com/ChocolateBread799/dotfiles/blob/main/config/awesome/config/picom.conf

backend = "glx";

shadow = true;
shadow-radius = 20;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.5;

fading = true;
fade-delta = 0.2;  # 30;
fade-in-step = 0.01;
fade-out-step = 0.01;
no-fading-openclose = false;

inactive-opacity = 0.80;
active-opacity = 1.00;
frame-opacity = 0.80;

shadow-exclude = [
    "class_g = 'Rofi'"
];

wintypes:
{
    tooltip = { fade = true; shadow = false; focus = true; };
    menu = { full-shadow = true;};
    popup_menu =  { full-shadow = true;};
    utility =  {full-shadow = true;};
    toolbar = {full-shadow = true;};
    normal = {full-shadow = true;};
    notification = {full-shadow = true;};
    dialog = {full-shadow = true};
    dock = {full-shadow = true;};
};

vsync = true;

blur-background = true;
#blur-method = "kawase";
blur-strength = 10;
blur-background-frame = false;
blur-background-fixed = false;
blur-kern = "11x11gaussian";

#blur: {
#  method = "dual_kawase";
#  strength = 9;
#  background = false;
#  background-frame = false;
#  background-fixed = false;
#}

