theme = "jellybeans"
#theme = "dark_high_contrast"

[editor]
bufferline = "always"
line-number = "relative"
rulers = [ 80, 100, 120 ]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[keys.normal]
C-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all"
]
A-x = "extend_to_line_bounds"
X = "select_line_above"
C-up = "move_visual_line_up"
C-down = "move_visual_line_down"
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
S-left = "extend_char_left"
S-right = "extend_char_right"
S-C-up = "extend_visual_line_up"
S-C-down = "extend_visual_line_down"
S-C-left = "extend_prev_word_start"
S-C-right = "extend_next_word_start"

[keys.insert]
k = { j = "normal_mode" }
C-s = [ ":write" ]
C-w = [ ":buffer-close", "normal_mode" ]
C-v = [ ":clipboard-paste-before" ]
C-up = "move_visual_line_up"
C-down = "move_visual_line_down"
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
S-left = "extend_char_left"
S-right = "extend_char_right"
S-C-up = "extend_visual_line_up"
S-C-down = "extend_visual_line_down"
S-C-left = "extend_prev_word_start"
S-C-right = "extend_next_word_start"

[keys.select]
y = [ ":clipboard-yank", "yank" ]
"`" = [ "normal_mode" ]
A-x = "extend_to_line_bounds"
X = "select_line_above"
