#basics-setup

# adam2 <hyphen color> <current dir> <user@host> <user input>
#if [[ $TERM != "screen" && $TERM != "xterm-256color" ]]; then
#    exec tmux
#elif [[ $TERM == "xterm-256color" ]]; then
#    # 256-color chart: https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg
#    prompt adam2 236 121 025 white
#else
#    prompt adam2 black green cyan white
#fi

# Set up paths
setupdir="$HOME/setup-scripts"
toolsdir="$setupdir/tools"
configdir="$setupdir/config-templates"

# Export PATH to toolsdir
export PATH="$HOME/bin:$toolsdir:$PATH"

# Set up aliases
source "$configdir/aliases"

# Set colors properly
export TERM=xterm-256color

# NOTE: must be at the end (aborts here if not interactive)
[[ $- != *i* ]] && return
TMUXBIN=$(which tmux)
if [ -z "$NOTMUX" ] && [ -n "$TMUXBIN" ] && [ -x "$TMUXBIN" ] && [[ -z "$TMUX" ]] ; then
    ID="$( tmux ls | grep -vm1 attached | cut -d: -f1 )" # get the id of a deattached session
    if [[ -z "$ID" ]] ;then # if not available create a new one
        exec tmux new-session
    else
        exec tmux attach-session -t "$ID" # if available attach to it
    fi
fi
