#basics-setup

# adam2 <hyphen color> <current dir> <user@host> <user input>
#if [[ $TERM != "screen" && $TERM != "xterm-256color" ]]; then
#    exec tmux
#elif [[ $TERM == "xterm-256color" ]]; then
#    # 256-color chart: https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg
#    prompt adam2 236 121 025 white
#else
#    prompt adam2 black green cyan white
#fi

# Set up paths
setupdir="$HOME/setup-scripts"
toolsdir="$setupdir/tools"
configdir="$setupdir/config-templates"

# Export PATH to toolsdir
export PATH="$HOME/bin:$toolsdir:$PATH"

# Set up aliases
source "$configdir/aliases"

# Set colors properly
export TERM=xterm-256color

# Force set key-bindings regardless of what the console app wants
case "${TERM}" in
  cons25*|linux) # plain BSD/Linux console
    bindkey '\e[H'    beginning-of-line   # home
    bindkey '\e[F'    end-of-line         # end
    bindkey '\e[5~'   delete-char         # delete
    bindkey '[D'      emacs-backward-word # esc left
    bindkey '[C'      emacs-forward-word  # esc right
    ;;
  *rxvt*) # rxvt derivatives
    bindkey '\e[3~'   delete-char         # delete
    bindkey '\eOc'    forward-word        # ctrl right
    bindkey '\eOd'    backward-word       # ctrl left
    # workaround for screen + urxvt
    bindkey '\e[7~'   beginning-of-line   # home
    bindkey '\e[8~'   end-of-line         # end
    bindkey '^[[1~'   beginning-of-line   # home
    bindkey '^[[4~'   end-of-line         # end
    ;;
  *xterm*) # xterm derivatives
    bindkey '\e[H'    beginning-of-line   # home
    bindkey '\e[F'    end-of-line         # end
    bindkey '\e[3~'   delete-char         # delete
    bindkey '\e[1;5C' forward-word        # ctrl right
    bindkey '\e[1;5D' backward-word       # ctrl left
    # workaround for screen + xterm
    bindkey '\e[1~'   beginning-of-line   # home
    bindkey '\e[4~'   end-of-line         # end
    ;;
  screen)
    bindkey '^[[1~'   beginning-of-line   # home
    bindkey '^[[4~'   end-of-line         # end
    bindkey '\e[3~'   delete-char         # delete
    bindkey '\eOc'    forward-word        # ctrl right
    bindkey '\eOd'    backward-word       # ctrl left
    bindkey '^[[1;5C' forward-word        # ctrl right
    bindkey '^[[1;5D' backward-word       # ctrl left
    ;;
esac

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
  SESSION_TYPE=remote/ssh
# many other tests omitted
else
  case $(ps -o comm= -p "$PPID") in
    sshd|*/sshd) SESSION_TYPE=remote/ssh;;
  esac
fi

# If we're running a remote session then we want to run tmux
# If we're NOT running a tiling window manager, we want to run tmux
if [ "$SESSION_TYPE" = "remote/ssh" ] || ! pgrep -x "i3" >/dev/null ; then
    WANT_TMUX="${WANT_TMUX:-yes}"
fi

# NOTE: must be at the end (aborts here if not interactive)
[[ $- != *i* ]] && return
TMUXBIN=$(which tmux)
if [ -n "$WANT_TMUX" ] && [ -z "$NOTMUX" ] && [ -n "$TMUXBIN" ] && [ -x "$TMUXBIN" ] && [[ -z "$TMUX" ]] ; then
    ID="$( tmux ls | grep -vm1 attached | cut -d: -f1 )" # get the id of a deattached session
    if [[ -z "$ID" ]] ;then # if not available create a new one
        exec tmux new-session
    else
        exec tmux attach-session -t "$ID" # if available attach to it
    fi
fi
