#!/bin/bash
die() { echo "$*" >&2 ; exit 1 ; }

usage() {
    echo "USAGE

    $0 [--push|--force-push] [--remote <remote>] [--track] [--keep] 
        [--base <base-branch>] [--fetch] [--fetch-remote <fetch-remote>]
        [--overwrite] [--stdin] <new-branch> [<commits...>]

    $0 --resume

    $0 --abort

    $0 --help

OPTIONS

    -p, --push
        Push the branch to the remote after splitting.

    -k, --keep
        Don't delete the branch after pushing to the remote. This is implied if
        no variant of --push is used.

    -f, --force-push
        Overwrite the remote branch when pushing. Implies --push.

    -u, --track
        Track the remote branch. Implies --keep.

    --remote <remote>
        Set the remote endpoint name to push to (default 'origin')

    --base <base-branch>
        Set the base branch for the new branch (otherwise, fork from HEAD)

    --fetch
        Fetch <base-branch> from <remote> before checkout

    --fetch-remote <fetch-remote>
        Fetch <base-branch> from <fetch-remote> instead of <remote>

    --overwrite
        If <new-branch> already exists, overwrite it

    --stdin
        Read a list of commits from stdin instead of from the command line

    --resume
        Resume an interrupted split, e.g. after resolving conflicts

    --abort
        Abort an in-progress split, or clean up state

    --help
        Show this help text
"
}

usage_error() {
    die "$* (see --help)" >&2
}

current_git_branch() {
    local original_branch
    original_branch="$(git branch --show-current)"
    if [ -z "$original_branch" ]; then
        original_branch="$(git rev-parse HEAD)"
    fi
    [ -n "$original_branch" ] || die "Failed to detect current branch"
    echo "$original_branch"
}

verify_current_git_branch() {
    [ -n "$git_split_new_branch" ] || die "Missing new branch name"
    [ "$(current_git_branch)" = "$git_split_new_branch" ] || die "Branches aren't in sync. Checkout $git_split_new_branch to resume."
}

set_config() {
    local key="$1"
    shift
    local value="$*"
    case "$key" in
        push)              git_split_push_branch="${value:-y}" ;;
        force_push)        git_split_do_force_push="${value:-y}" ;;
        remote)            git_split_push_remote="${value:-origin}" ;;
        track)             git_split_track_remote="${value:-y}" ;;
        keep_branch)       git_split_keep_branch="${value:-y}" ;;
        original_branch)   git_split_original_branch="${value}" ;;
        new_branch)        git_split_new_branch="${value}" ;;
    esac
}

print_config() {
    echo "push=$git_split_push_branch"
    echo "keep_branch=$git_split_keep_branch"
    echo "force_push=$git_split_do_force_push"
    echo "remote=$git_split_push_remote"
    echo "track=$git_split_track_remote"
    echo "original_branch=$git_split_original_branch"
    echo "new_branch=$git_split_new_branch"
}

write_config() {
    [ -n "$splitConfig" ] || die "Config path not set"
    print_config > "$splitConfig" || die "Failed to write config to $splitConfig"
}

read_config() {
    [ -n "$splitConfig" ] || die "Config path not set"
    [ -f "$splitConfig" ] || die "Unreadable config: $splitConfig"

    # Parse the config
    while IFS= read -r line
    do
        key="$(echo "$line" | cut -d'=' -f1)" || die "Malformed config in $splitConfig"
        value="$(echo "$line" | cut -d'=' -f2-)" || die "Malformed config in $splitConfig"
        if [ -n "$key" ]; then
            set_config "$key" "$value"
        fi
    done <"$splitConfig"
}

do_abort_split() {
    # Abort any existing cherry-pick
    git cherry-pick --abort 2>/dev/null || :

    # Try and switch back to the old branch if possible
    if [ -n "$git_split_original_branch" ]; then
        git checkout "$git_split_original_branch" || :
    fi

    # Clean up config file
    rm -f "$splitConfig"
}

do_push_split() {
    verify_current_git_branch
    [ -n "$git_split_push_remote" ] || die "Missing push remote"

    local push_params
    [ -n "$git_split_do_force_push" ] && push_params+=( "-f" )
    [ -n "$git_split_track_remote" ] && push_params+=( "-u" )
    
    # Push the branch to origin or wherever
    git push "${push_params[@]}" "$git_split_push_remote" "$git_split_new_branch:$git_split_new_branch" \
        || die "Failed to push $git_split_new_branch to $git_split_push_remote"

    # Revert to the original branch
    git checkout "$git_split_original_branch" || die "Failed to checkout original branch $git_split_original_branch"

    # Delete the new branch
    if [ -z "$git_split_keep_branch" ]; then
        git branch --delete --force "$git_split_new_branch" || :
    fi
}

do_finish_split() {
    verify_current_git_branch
    [ -n "$git_split_original_branch" ] || die "Missing original branch"

    # push?
    if [ -n "$git_split_push_branch" ]; then
        do_push_split
    else
        echo "Done. Push using:"
        echo "  git push ${push_params[@]} '$git_split_push_remote' '$git_split_new_branch:$git_split_new_branch'"
    fi

    # Clean up config file
    rm -f "$splitConfig"
}

do_resume_split() {
    local do_resume do_abort
    while [ -n "$1" ]; do
        case "$1" in
        --resume|-r)    do_resume=y ;;
        --abort)        do_abort=y ;;
        --help)         usage ; exit 0 ;;
        *)              usage_error "Unknown parameter '$1'";;
        esac
        shift
    done

    if [ -n "$do_resume" ] && [ -n "$do_abort" ]; then
        usage_error "--resume and --abort are mutually exclusive."
    fi
    if [ -z "$do_resume" ] && [ -z "$do_abort" ]; then
        usage_error "Looks like a split is in progress. Use --resume or --abort."
    fi

    if [ -n "$do_abort" ]; then
        do_abort_split
    else
        # Load the config
        read_config

        # Check we're still on the right branch
        verify_current_git_branch

        # Resume the cherry-pick
        git cherry-pick --resume || die "Failed to resume cherry-pick"

        # Finalize
        do_finish_split
    fi
}

check_param() {
    case "$2" in
    -*|"")     usage_error "Expected parameter for '$1'" ;;
    *)         : ;;
    esac
}

do_init_split() {
    # Set some sensible defaults
    set_config "remote" "origin"

    # Parse the config
    local do_stdin commit_range original_branch new_branch base_branch checkout_opts
    local do_fetch fetch_remote
    while [ -n "$1" ]; do
        case "$1" in
        --keep|-k)          set_config "keep_branch" "y" ;;
        --push|-p)          set_config "push" "y" ;;
        --force-push|-f)    set_config "push" "y" ; set_config "force_push" "y" ;;
        --track|-u)         set_config "keep_branch" "y" ; set_config "track" "y" ;;
        --remote)           check_param "$1" "$2" ; set_config "remote" "$2" ; shift ;;
        --base)             check_param "$1" "$2" ; base_branch="$2" ; shift ;;
        --fetch-remote)     check_param "$1" "$2" ; fetch_remote="$2" ; do_fetch=y ; shift ;;
        --overwrite)        checkout_opts+=( "-f" ) ;;
        --fetch)            do_fetch=y ;;
        --stdin)            do_stdin=true ;;
        --abort)            die "Nothing to abort." ;;
        --resume)           die "Nothing to resume." ;;
        --help)             usage ; exit 0 ;;
        --)                 break ;;
        -*)                 usage_error "Unknown option '$1'" ;;
        *)                  break ;;
        esac
        shift
    done

    # If the branch isn't being pushed, then set keep to true
    if [ -z "$git_split_push_branch" ]; then
        set_config "keep" "y"
    fi

    # Detect current head
    set_config "original_branch" "$(current_git_branch)"

    # Fetch the branch from the remote if requested
    if [ -n "$do_fetch" ]; then
        [ -z "$base_branch" ] && die "--fetch requires --base"
        [ -z "$fetch_remote" ] && fetch_remote="$git_split_push_remote"
        [ -z "$fetch_remote" ] && fetch_remote="origin"

        git fetch "$fetch_remote" "$base_branch" || die "Failed to fetch $base_branch"

        # change base branch to remote/branch
        base_branch="$fetch_remote/$base_branch"
    fi

    # Get the new branch name
    new_branch="$1" ; shift ;
    [ -n "$new_branch" ] || usage_error "Expected branch name"
    set_config "new_branch" "$new_branch"

    # Get the commit range
    declare -a commit_range
    if [ -n "$do_stdin" ]; then
        # Read commits from file
        while IFS= read -r line
        do
            [ -n "$line" ] || continue

            # Get the hash
            commit_hash="$(echo "$line" | cut -d' ' -f1)" || die "Malformed config in $splitConfig"
            [ -n "$commit_hash" ] || continue

            # Validate it
            git cat-file commit "$commit_hash" >/dev/null 2>&1 || die "Unknown git hash '$commit_hash'"

            # Save it
            commit_range+=( "$commit_hash" )
        done
    else
        # Read from command line
        [ -n "$1" ] || usage_error "Expected commit range or --stdin"
        while [ -n "$1" ]; do
            commit_range+=( "$1" )
            shift
        done
    fi

    # Write the config to the split config file
    write_config

    # Checkout the branch
    if [ -n "$base_branch" ]; then
        git checkout "${checkout_opts[@]}" -B "$new_branch" "$base_branch" || die "Failed to checkout $new_branch (base: $base_branch)"
    else
        git checkout "${checkout_opts[@]}" -b "$new_branch" || die "Failed to checkout $new_branch"
    fi

    # Begin the cherry-pick
    git cherry-pick "${commit_range[@]}" || die "Cherry pick failed. Try --resume once you've fixed whatever's up."

    # Finalize if this was successful
    do_finish_split
}

#
# Entry point
#

gitRoot="$(git rev-parse --show-toplevel)" || die "Failed to find git root"
gitConfigRoot="$gitRoot/.git"

splitConfig="$gitConfigRoot/split-config"
if [ -f "$splitConfig" ]; then
    # Run in "continue" mode
    do_resume_split "$@"
else
    # Initialize the config
    do_init_split "$@"
fi
