#!/bin/bash
cd "$(realpath "$(git rev-parse --show-toplevel)")"
git reset .
git checkout .
git clean -ffxd .
git submodule update --init --recursive
git submodule foreach 'git reset . ; git checkout . ; git clean -ffxd . '
