#!/bin/bash
port="80"
public="no"

die() {
    echo "$*" >&2
    exit 1
}

validate_param() {
    [[ $1 =~ ^[0-9]+ ]] || die "Invalid parameter '$1'"
}

while [[ $1 =~ --* ]]; do
    case "$1" in
    --port) validate_param "$2"; port="$2"; shift ;;
    --public) public="yes" ;;
    *) break;
    esac
    shift
done

args=()
if [ "$public" == "no" ]; then
    args+=( --bind "127.0.0.1" )
fi 

exec python3 -m http.server "${args[@]}" "$port" "$@"
