#!/bin/bash
die() { echo "$*" >&2 ; exit 1 ; }
here="$(dirname "$(basename "$0")")"
source="$here/Journal"
target="$here/Journal.mount"
marktextFlatpak=com.github.marktext.marktext

open_journal() {
    if mountpoint -q "$target" ; then
        die "Already mounted."
    fi
    mkdir -p "$target" || die "Failed to create $target"
    sudo cryptsetup luksOpen "$source" journal || die "Failed to open $source"
    sudo mount "/dev/mapper/journal" "$target" || die "Failed to mount"
}

open_marktext() {
    flatpak list --app | grep -q "$marktextFlatpak" || \
        die "Marktext not installed"
    flatpak run "$marktextFlatpak" "$target" >/dev/null 2>&1
}

open_marktext_async() {
    if flatpak list --app | grep -q "$marktextFlatpak"; then
        nohup flatpak run "$marktextFlatpak" "$target" >/dev/null 2>&1 &
    fi
}

close_journal() {
    sudo umount "$target" || die "Failed to umount $target"
    sudo cryptsetup luksClose journal || die "Failed to close"
}

check_closed() {
    # ensure all files are gone!
    wc="$(find "$target" -mindepth 1 | wc -l)"
    if [ "$wc" != "0" ]; then
        echo "Warning: directory doesn't appear to be empty!" >&2
    fi

    echo | xclip # clear clipboard, just in case
}

if [ "$1" == "open" ]; then
    open_journal
    open_marktext_async
elif [ "$1" == "close" ]; then
    close_journal
    check_closed
elif [ -z "$1" ]; then
    open_journal
    open_marktext
    close_journal
    check_closed
else
    die "Expected: open or close"
fi

